"""add_missing_constraints

Revision ID: 6e3d8fd2ff05
Revises: d9d764d1e861
Create Date: 2026-05-12 12:15:50.217787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3d8fd2ff05'
down_revision: Union[str, Sequence[str], None] = 'd9d764d1e861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
