"""initial_schema

Revision ID: d9d764d1e861
Revises: 
Create Date: 2026-05-12 12:05:17.952454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9d764d1e861'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('assignments', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('assignments', 'estimated_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('courses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('courses', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('study_sessions', 'scheduled_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('study_sessions', 'scheduled_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'hashed_password')
    op.alter_column('study_sessions', 'scheduled_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('study_sessions', 'scheduled_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('courses', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('courses', 'created_at')
    op.alter_column('assignments', 'estimated_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assignments', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('assignments', 'created_at')
    # ### end Alembic commands ###
